USE escola;

INSERT INTO alunos (nome, email, curso) VALUES
('João Silva', 'joao.silva@gmail.com', 'Informática'),
('Maria Souza', 'maria.souza@gmail.com', 'Administração'),
('Pedro Santos', 'pedro.santos@gmail.com', 'Desenvolvimento de Sistemas'),
('Ana Oliveira', 'ana.oliveira@gmail.com', 'Enfermagem'),
('Lucas Costa', 'lucas.costa@gmail.com', 'Eletrônica'),
('Beatriz Almeida', 'beatriz.almeida@gmail.com', 'Informática'),
('Gabriel Rodrigues', 'gabriel.rodrigues@gmail.com', 'Desenvolvimento de Sistemas'),
('Juliana Ferreira', 'juliana.ferreira@gmail.com', 'Administração'),
('Rafael Martins', 'rafael.martins@gmail.com', 'Eletrônica'),
('Camila Barbosa', 'camila.barbosa@gmail.com', 'Enfermagem'),
('Matheus Gomes', 'matheus.gomes@gmail.com', 'Informática'),
('Larissa Ribeiro', 'larissa.ribeiro@gmail.com', 'Administração'),
('Gustavo Carvalho', 'gustavo.carvalho@gmail.com', 'Desenvolvimento de Sistemas'),
('Amanda Lima', 'amanda.lima@gmail.com', 'Enfermagem'),
('Felipe Rocha', 'felipe.rocha@gmail.com', 'Eletrônica'),
('Isabela Martins', 'isabela.martins@gmail.com', 'Informática'),
('Bruno Alves', 'bruno.alves@gmail.com', 'Administração'),
('Mariana Lopes', 'mariana.lopes@gmail.com', 'Desenvolvimento de Sistemas'),
('Thiago Nunes', 'thiago.nunes@gmail.com', 'Eletrônica'),
('Leticia Mendes', 'leticia.mendes@gmail.com', 'Enfermagem'),
('Daniel Teixeira', 'daniel.teixeira@gmail.com', 'Informática'),
('Carolina Castro', 'carolina.castro@gmail.com', 'Administração'),
('Eduardo Moreira', 'eduardo.moreira@gmail.com', 'Desenvolvimento de Sistemas'),
('Sofia Correia', 'sofia.correia@gmail.com', 'Enfermagem'),
('Henrique Vieira', 'henrique.vieira@gmail.com', 'Eletrônica'),
('Bianca Cardoso', 'bianca.cardoso@gmail.com', 'Informática'),
('Leonardo Ramos', 'leonardo.ramos@gmail.com', 'Administração'),
('Nicole Duarte', 'nicole.duarte@gmail.com', 'Desenvolvimento de Sistemas'),
('Vinicius Monteiro', 'vinicius.monteiro@gmail.com', 'Eletrônica'),
('Clara Fernandes', 'clara.fernandes@gmail.com', 'Enfermagem'),
('Arthur Mendes', 'arthur.mendes@gmail.com', 'Informática'),
('Luana Freitas', 'luana.freitas@gmail.com', 'Administração'),
('Diego Batista', 'diego.batista@gmail.com', 'Desenvolvimento de Sistemas'),
('Manuela Reis', 'manuela.reis@gmail.com', 'Enfermagem'),
('Caio Farias', 'caio.farias@gmail.com', 'Eletrônica'),
('Valentina Moraes', 'valentina.moraes@gmail.com', 'Informática'),
('Rodrigo Pires', 'rodrigo.pires@gmail.com', 'Administração'),
('Alice Tavares', 'alice.tavares@gmail.com', 'Desenvolvimento de Sistemas'),
('Samuel Borges', 'samuel.borges@gmail.com', 'Eletrônica'),
('Helena Cunha', 'helena.cunha@gmail.com', 'Enfermagem'),
('Miguel Andrade', 'miguel.andrade@gmail.com', 'Informática'),
('Laura Neves', 'laura.neves@gmail.com', 'Administração'),
('Enzo Moura', 'enzo.moura@gmail.com', 'Desenvolvimento de Sistemas'),
('Yasmin Araujo', 'yasmin.araujo@gmail.com', 'Enfermagem'),
('Nicolas Peixoto', 'nicolas.peixoto@gmail.com', 'Eletrônica'),
('Livia Guimaraes', 'livia.guimaraes@gmail.com', 'Informática'),
('Andre Sales', 'andre.sales@gmail.com', 'Administração'),
('Isadora Campos', 'isadora.campos@gmail.com', 'Desenvolvimento de Sistemas'),
('Murilo Braga', 'murilo.braga@gmail.com', 'Eletrônica'),
('Melissa Pinto', 'melissa.pinto@gmail.com', 'Enfermagem');